spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp

myconfig:
  welcome:
    message: Hello,
    img: hello.img

msg:
  title: Spring Boot + Thymeleaf CRUD Example